server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    username: 'mesh'
    url: jdbc:postgresql://localhost:5432/customer
    password: '!maleSy06*'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
       ddl-auto: create

    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/